### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by ghost** [devdutchy/warthunder-rpc#2]
When I run `npm start`, it displays the following error:
![image](https://user-images.githubusercontent.com/32337790/113446497-2a8d2e00-93f8-11eb-964c-a723b81b62e8.png)

**Comment by Jackaroo05** [comment]
I have the same issue. How do I fix it?

**Comment by Jackaroo05** [comment]
Update: contacted dev on discord and repo is not maintained

**Comment by devdutchy** [comment]
repo's no longer maintained, closing.
